name: ac_india
channels:
  - conda-forge
  - nodefaults
dependencies:
  - spyder
  - pandas
  - geopandas
  - matplotlib
  - tqdm
  - cartopy
  - xarray
  - netCDF4
  - rioxarray
  - numpy
  - seaborn
  - shapely
  - openpyxl
